"""Add memory_notes, language_preference to participants and summary to conversations

Revision ID: 323503d1b1f5
Revises: 5def02b6bd4e
Create Date: 2026-03-23 11:42:20.861578
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323503d1b1f5'
down_revision: Union[str, None] = '5def02b6bd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('participants', sa.Column('memory_notes', sa.Text(), nullable=True))
    op.add_column('participants', sa.Column('language_preference', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'language_preference')
    op.drop_column('participants', 'memory_notes')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
