"""initial schema

Revision ID: 3673c0f43f1c
Revises: 
Create Date: 2026-03-20 12:17:30.097986
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3673c0f43f1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invite_code', sa.String(length=8), nullable=False),
    sa.Column('arm', sa.Enum('control', 'analytic', 'constructive', name='armtype'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('venture_name', sa.String(length=300), nullable=True),
    sa.Column('venture_description', sa.Text(), nullable=True),
    sa.Column('industry_vertical', sa.String(length=100), nullable=True),
    sa.Column('baseline_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('cohort_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('enrolled', 'active', 'completed', 'dropped', name='participantstatus'), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_consent', sa.Boolean(), nullable=False),
    sa.Column('audio_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index('idx_participants_arm', 'participants', ['arm'], unique=False)
    op.create_index('idx_participants_cohort', 'participants', ['cohort_id'], unique=False)
    op.create_index('idx_participants_status', 'participants', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('initiated_by', sa.Enum('system', 'participant', name='initiatortype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_participant', 'conversations', ['participant_id'], unique=False)
    op.create_table('invite_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('arm', sa.Enum('control', 'analytic', 'constructive', name='armtype'), nullable=False),
    sa.Column('cohort_id', sa.String(length=50), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['used_by'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_table('surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('baseline', 'weekly_pulse', 'midpoint', 'endline', name='surveytype'), nullable=False),
    sa.Column('responses', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_surveys_participant', 'surveys', ['participant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_method', sa.Enum('text', 'voice', name='inputmethod'), nullable=False),
    sa.Column('audio_file_url', sa.Text(), nullable=True),
    sa.Column('token_usage', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('synced', 'pending', 'failed', name='syncstatus'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index('idx_messages_client_id', 'messages', ['client_id'], unique=False)
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('sent', 'delivered', 'opened', 'failed', name='notificationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_participant', 'notifications', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_participant', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_index('idx_messages_client_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_surveys_participant', table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index('idx_conversations_participant', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_participants_status', table_name='participants')
    op.drop_index('idx_participants_cohort', table_name='participants')
    op.drop_index('idx_participants_arm', table_name='participants')
    op.drop_table('participants')
    op.drop_table('admin_users')
    op.drop_table('admin_events')
    # ### end Alembic commands ###
