"""Add otp_code and otp_expires to participants

Revision ID: b73391c6438f
Revises: f7058cd477ee
Create Date: 2026-03-23 13:47:47.354053
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b73391c6438f"
down_revision: Union[str, None] = "f7058cd477ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participants", sa.Column("otp_code", sa.String(length=6), nullable=True)
    )
    op.add_column(
        "participants",
        sa.Column("otp_expires", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participants", "otp_expires")
    op.drop_column("participants", "otp_code")
    # ### end Alembic commands ###
