"""Add password_hash to participants

Revision ID: f7058cd477ee
Revises: 323503d1b1f5
Create Date: 2026-03-23 12:01:40.771702
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7058cd477ee'
down_revision: Union[str, None] = '323503d1b1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'password_hash')
    # ### end Alembic commands ###
